"""showrunner CLI.

Every subcommand that can refuse does so with exit code 2 — the Claude Code PreToolUse
"deny the tool call" code — so `lock guard` and `stop-gate` work unchanged as hooks.
"""

import argparse
import json
import os
import shutil
import sys

from . import (__version__, brief, campaign, collide, config, dispatch, events, gates,
               graph as G, harness, lanes, lease, locks, worktree)
from .util import Refused, die, eprint, rel, run, slug

BOLD, DIM, RED, GRN, YEL, OFF = "\033[1m", "\033[2m", "\033[31m", "\033[32m", "\033[33m", "\033[0m"
if not sys.stdout.isatty() or os.environ.get("NO_COLOR"):
    BOLD = DIM = RED = GRN = YEL = OFF = ""


def _cfg(args, required=True):
    cfg = config.load(required=required)
    return cfg


def _graph(cfg):
    return G.open_graph(cfg)


# ------------------------------------------------------------------- init
EXAMPLE = {
    "project_name": None,
    "graph": {"backend": "auto", "db": ".showrunner/graph.db", "br_db": None},
    "lock_root": None,
    "resources": [
        {"name": "device", "match": ["\\bdeploy\\b", "\\bflutter(-tizen)? run\\b"],
         "note": "the physical device / deploy target — one consumer at a time"}
    ],
    "lanes": [
        {"name": "device-work", "lane": "serialized", "resource": "device",
         "match": {"labels": ["device", "deploy"], "title": "deploy|device|on-device"}},
        {"name": "pure-logic", "lane": "headless",
         "match": {"labels": ["backend", "test", "docs", "analysis"]}}
    ],
    "default_lane": "serialized",
    "worktree_root": ".worktrees",
    "scratch_root": ".showrunner/scratch",
    "inject": [
        {"path": ".env", "mode": "symlink", "optional": True}
    ],
    "checks": [
        {"name": "tests", "cmd": "echo 'configure me: your test command'"}
    ],
    "collision": {
        "extra_globs": [],
        "always_serialize": ["test/**", "tests/**"]
    },
    "shared_state": [],
    "harness": {
        "provision": "auto",
        "require": True,
        "installer": None,
        "_note": "The per-agent harness is auto-detected. showrunner ASKS it which files are "
                 "rules and whether a worktree matches its parent — it keeps no list of its "
                 "own. Track the harness dir in git (simplest: it then crosses into every "
                 "worktree by itself), or set \"installer\" to the path of its install script "
                 "so each worktree is provisioned with the PARENT's rules. Never let a worktree "
                 "get freshly-seeded rules: an installer seeds user-owned files only when "
                 "absent, so a blank verify.yaml means a commit gate that owes nothing and "
                 "reports success."
    }
}


def cmd_init(args):
    cfg = config.load(required=False)
    if os.path.exists(cfg.path) and not args.force:
        die("%s already exists (use --force to overwrite)" % rel(cfg.path, cfg.root), code=2)
    data = dict(EXAMPLE)
    data["project_name"] = os.path.basename(cfg.root)
    cfg.data = data
    path = config.write(cfg)
    os.makedirs(cfg.state_dir, exist_ok=True)
    gi = os.path.join(cfg.state_dir, ".gitignore")
    if not os.path.exists(gi):
        with open(gi, "w") as fh:
            # bin/ and lib/ ARE THE TOOL, not this project. CI-01 measured what happens when
            # they are neither tracked nor ignored: a fresh install staged 31 paths on the
            # consumer's next `git add -A`, showrunner's whole library and the installing
            # machine's .pyc among them, and the vendored copy is then what drifts. install.sh
            # closes that hole — and `init` places the same two directories, so writing this
            # list without them reopens it through the other door.
            #
            # events.jsonl belongs here for the ordinary reason: it is an observation of a
            # campaign, regenerated by working, and committing it would make one machine's
            # view of a run part of everyone's source.
            fh.write("# showrunner runtime state — not source\n"
                     "graph.db\ngraph.db-*\nlocks/\nscratch/\ncampaign.json\n"
                     "routing.jsonl\nwaiting.jsonl\nevents.jsonl\n*.lock\n"
                     "baseline.json\nintegration-commit.json\n"
                     "\n# The TOOL, not this project — replaced wholesale on upgrade.\n"
                     "bin/\nlib/\n")
    worktree.ensure_root(cfg)
    # PLACE THE BINARY EVERY BRIEF WILL NAME. install.sh copies it and then calls init, so this
    # was only ever missing for someone who ran init directly — and what they got was a repo
    # that reported ready while every brief it produced named a path that did not exist. The
    # remedy `showrunner init` has to leave the person unstuck, not merely exit 0.
    # AND THE LIBRARY BESIDE IT. The binary is a launcher that resolves `lib/showrunner` next to
    # itself and refuses without it, so copying it alone produced a file that existed, was
    # executable, and died on every invocation — the second time this exact shape has shipped
    # here. `install.sh` always copied both; `init` copied one and reported success, which is
    # how "placed the path every brief names" became true and useless in the same sentence.
    here = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    src = os.path.join(here, "bin", "showrunner")
    src_lib = os.path.join(here, "lib", "showrunner")
    dst = os.path.join(cfg.state_dir, "bin", "showrunner")
    dst_lib = os.path.join(cfg.state_dir, "lib", "showrunner")
    if os.access(src, os.R_OK) and os.path.isdir(src_lib) and not os.access(dst, os.X_OK) \
            and os.path.realpath(src) != os.path.realpath(dst):
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        os.makedirs(os.path.dirname(dst_lib), exist_ok=True)
        if os.path.isdir(dst_lib):
            shutil.rmtree(dst_lib)
        shutil.copytree(src_lib, dst_lib)
        shutil.copy2(src, dst)
        os.chmod(dst, 0o755)
        print("placed %s and its library (the path every Crawler brief names)"
              % rel(dst, cfg.root))
    print("wrote %s" % rel(path, cfg.root))
    print("wrote %s" % rel(gi, cfg.root))
    print("created %s (gitignored — Crawler worktrees live INSIDE the repo, see issue #4)"
          % rel(cfg.worktree_root, cfg.root))
    print("\nNext: edit the config (resources, lanes, checks, inject), then `showrunner doctor`.")
    return 0


# ----------------------------------------------------------------- doctor
def cmd_doctor(args):
    cfg = _cfg(args, required=False)
    print("%sshowrunner %s%s  ·  repo %s" % (BOLD, __version__, OFF, cfg.root))
    print("config: %s%s" % (rel(cfg.path, cfg.root),
                            "" if os.path.exists(cfg.path) else "  (MISSING — run `showrunner init`)"))
    findings = cfg.validate()
    bad = 0
    if not os.path.exists(cfg.path):
        # EXIT 2, not a decorated header line. doctor validated the DEFAULTS and reported every
        # check passing, in a repo nobody had configured — a true answer to a question the
        # person asking had not asked. The remedy was printed and the exit code said go, so
        # anything gating on this verb (a CI step, an agent reading `$?`) read an uninitialised
        # repo as a healthy one. Running pre-init is still supported and still prints the whole
        # report; what it no longer does is call that success.
        findings = [("error", "no config at %s — every check below ran against DEFAULTS, not "
                              "against anything you chose. Run `showrunner init`."
                              % rel(cfg.path, cfg.root))] + list(findings)
    for level, msg in findings:
        mark = {"error": RED + "ERROR" + OFF, "warn": YEL + "warn " + OFF, "ok": GRN + "ok   " + OFF}[level]
        print("  %s %s" % (mark, msg))
        bad += level == "error"

    backend = "?"
    try:
        g = _graph(cfg)
        backend = g.name
        print("  %s graph backend: %s (%s)" % (GRN + "ok   " + OFF, backend,
                                               cfg.graph_db if backend == "vendored" else cfg.br_db or "br"))
    except Refused as exc:
        print("  %s graph backend: %s" % (RED + "ERROR" + OFF, exc))
        bad += 1

    if backend == "br":
        # Honesty about the boundary: this adapter has not been exercised against a real
        # br install on this machine, and saying so is cheaper than a surprise mid-run.
        print("  %s the br adapter parses `br --json` output strictly and REFUSES on an "
              "unrecognised shape rather than reporting an empty graph. If br changes its "
              "output you will get a loud error, not a silent no-op." % (YEL + "note " + OFF))

    ls = locks.LockSet(cfg)
    if ls.names():
        print("  %s resources: %s" % (GRN + "ok   " + OFF, ", ".join(ls.names())))
        for name in ls.names():
            state, h = locks.Lock(ls.root, name).state()
            if state != locks.FREE:
                print("        %s: %s (pid %s, %s)" % (name, state, h.get("pid"), h.get("who")))
    else:
        print("  %s no resources configured — nothing is serialized, so `default_lane: "
              "serialized` has no lock to take." % (YEL + "warn " + OFF))

    for line in harness.report(cfg):
        print("  %s %s" % (GRN + "ok   " + OFF, line))
    gap = worktree.harness_gap(cfg)
    if gap and not harness.spec(cfg)["dirs"]:
        print("  %s %s" % (YEL + "warn " + OFF, gap))

    # THE UPGRADE WINDOW. Between upgrading the harness and committing it, the orchestrator runs
    # scripts a Crawler cannot have: `git worktree add` copies TRACKED files, so a new worktree
    # gets HEAD's payload, not the working tree's. Spawn already refuses — correctly, and loudly
    # — but it refuses one Crawler at a time, in the middle of a fan-out, which is the worst
    # moment to discover a condition that has been true since the upgrade. It is knowable now.
    if os.path.isdir(os.path.join(cfg.root, ".game_loop")):
        rc, out, _ = run(["git", "diff", "HEAD", "--name-only", "--", ".game_loop/bin/"],
                         cwd=cfg.root)
        pending = [x for x in (out or "").split() if x]
        if rc == 0 and pending:
            print("  %s the harness payload is upgraded but NOT COMMITTED (%s). A worktree gets "
                  "HEAD's copy, so every spawn will refuse until this is committed — commit "
                  "first, then fan out." % (YEL + "warn " + OFF, ", ".join(pending[:3])))

    # THE RECIPROCAL HALF: showrunner's config names paths into a NEIGHBOUR's tree, and only
    # this repo can see whether they still resolve. A neighbour who moves or uninstalls their
    # tool cannot fail our suite — they do not know we point at them — so the failure would
    # otherwise surface one Crawler at a time, as a soft warning, mid-fan-out. Configured-and-
    # missing and never-configured are different states and used to print the same thing.
    chat_cfg = (dispatch.dispatch_config(cfg).get("chat") or {})
    if chat_cfg.get("enabled"):
        for key in ("cli", "installer"):
            path = dispatch.chat_path(cfg, key)
            if not path:
                print("  %s chat is enabled but dispatch.chat.%s is unset — Crawlers will spawn "
                      "unreachable" % (YEL + "warn " + OFF, key))
            elif not os.path.exists(path):
                print("  %s dispatch.chat.%s points at %s, which does not exist. A neighbour "
                      "moving their checkout cannot fail our suite, so this is the only place "
                      "it shows." % (RED + "ERROR" + OFF, key, path))
                bad += 1
            else:
                print("  %s chat %s resolves: %s" % (GRN + "ok   " + OFF, key, path))

    # THE WATCHDOG THAT CANNOT SEE A SUBAGENT (issue #23). `showrunner waiting` was built for
    # exactly one consumer and nothing connects them, so the default state of a two-layer
    # install is: the guard exists, the answer exists, and they are not talking. The failure is
    # silent in the direction that trains people to ignore alarms — an orchestrator that has
    # correctly dispatched a full wave gets rung, then pages the human, and the operator raises
    # the idle threshold until the genuinely wedged run is invisible too.
    for dirname in harness.spec(cfg)["dirs"]:
        state, detail = harness.waiting_probe(cfg, dirname)
        if state is None:
            continue
        if state == "armed":
            print("  %s %s's idle watchdog is wired to an answer about dispatched work: %s"
                  % (GRN + "ok   " + OFF, dirname, detail))
        elif state == "failing":
            print("  %s %s's waiting probe is CONFIGURED AND FAILING (%s). 'could not answer' "
                  "rings and reports failing, so this reads as a broken watchdog rather than "
                  "as the config error it is — check the path is absolute and executable."
                  % (RED + "ERROR" + OFF, dirname, detail or "no command"))
            bad += 1
        else:
            print("  %s %s's idle watchdog has NO waiting probe, so a fanned-out orchestrator "
                  "waiting on Crawlers it cannot hurry looks identical to one that fell asleep "
                  "— it gets rung, and at the ring cap it pages a human for a healthy run.\n"
                  "        A human arms this once per install, deliberately: a verb showrunner "
                  "could call would be callable by the sessions being watched, and a probe of "
                  "`true` is the watchdog switched off by the thing it watches.\n"
                  "        Set %s to:\n            %s waiting"
                  % (YEL + "warn " + OFF, dirname, detail or "the harness's waiting-probe key",
                     brief.sr_bin(cfg)))

    # THE BINARY EVERY BRIEF NAMES. A Crawler's proof-of-done, its close, its stop-gate trigger
    # all route through one absolute path, and this repo spent a week naming one that did not
    # exist — `install.sh` places it and a development checkout never runs its own installer.
    # Absolute and canonical and dead reads exactly like absolute and correct.
    sr = brief.sr_bin(cfg)
    if os.access(sr, os.X_OK):
        print("  %s the binary every brief names resolves: %s" % (GRN + "ok   " + OFF, rel(sr, cfg.root)))
    else:
        print("  %s %s does not exist or is not executable, and every Crawler brief tells its "
              "agent to run it. Run install.sh, or work from a checkout that carries "
              "bin/showrunner." % (RED + "ERROR" + OFF, sr))
        bad += 1

    if gates.load_baseline(cfg) is None:
        print("  %s no baseline recorded — `showrunner baseline` on a known-good tree, or "
              "integration cannot tell a new failure from a pre-existing one." % (YEL + "warn " + OFF))
    return 2 if bad else 0


# ----------------------------------------------------------------- status
def cmd_status(args):
    cfg = _cfg(args)
    g = _graph(cfg)
    ready = g.ready()
    in_prog = [x for x in g.list(status=G.IN_PROGRESS) if not x.is_epic]
    print("%s%s%s — graph %s" % (BOLD, cfg.project_name, OFF, g.name))
    print("  ready: %d   in progress: %d   done: %d   refuted: %d"
          % (len(ready), len(in_prog), len(g.list(status=G.CLOSED)), len(g.list(status=G.REFUTED))))
    for leaf in ready[:20]:
        d = lanes.route(cfg, leaf)
        print("  %sready%s  %-16s %-9s %s" % (GRN, OFF, leaf["id"], d["lane"], leaf.get("title", "")[:70]))
    for leaf in in_prog:
        tag = "parked" if leaf.get("parked") else "claimed"
        print("  %s%s%s %-16s %-9s %s" % (YEL, tag, OFF, leaf["id"], leaf.get("actor") or "?",
                                          leaf.get("title", "")[:70]))
    ls = locks.LockSet(cfg)
    for name in ls.names():
        state, h = locks.Lock(ls.root, name).state()
        if state != locks.FREE:
            print("  lock %-10s %s by pid %s (%s)" % (name, state, h.get("pid"), h.get("who")))
    try:
        stale = g.stale_claims()
    except Refused:
        stale = []
    if stale:
        print("  %s%d stale claim(s)%s — run `showrunner reap`" % (RED, len(stale), OFF))
    return 0


# ------------------------------------------------------------------ graph
def cmd_add(args):
    cfg = _cfg(args)
    g = _graph(cfg)
    body = args.body or ""
    if args.body_file:
        with open(args.body_file) as fh:
            body = fh.read()
    leaf_id = g.add(args.title, body=body, kind=args.kind, leaf_id=args.id,
                    labels=args.label or [], paths=args.path or [])
    for parent in args.after or []:
        g.dep(leaf_id, parent)
    events.emit(cfg, "leaf.added", {"leaf": leaf_id, "title": args.title, "leaf_kind": args.kind,
                "labels": args.label or [], "after": args.after or []})
    print(leaf_id)
    return 0


def cmd_dep(args):
    cfg = _cfg(args)
    _graph(cfg).dep(args.child, args.parent)
    print("%s is blocked by %s" % (args.child, args.parent))
    return 0


def cmd_list(args):
    cfg = _cfg(args)
    leaves = _graph(cfg).list(status=args.status)
    if args.json:
        print(json.dumps(leaves, indent=2, sort_keys=True))
        return 0
    for leaf in leaves:
        print("%-16s %-12s %-8s %s" % (leaf["id"], leaf["status"], leaf["kind"], leaf.get("title", "")))
    return 0


def cmd_show(args):
    cfg = _cfg(args)
    leaf = _graph(cfg).show(args.id)
    print(json.dumps(leaf, indent=2, sort_keys=True))
    return 0


def cmd_ready(args):
    cfg = _cfg(args)
    ready = _graph(cfg).ready()
    if args.json:
        print(json.dumps(ready, indent=2, sort_keys=True))
        return 0
    for leaf in ready:
        print("%-16s %s" % (leaf["id"], leaf.get("title", "")))
    return 0


def cmd_claim(args):
    cfg = _cfg(args)
    g = _graph(cfg)
    if args.next:
        leaf = g.claim_next(args.actor, pid=args.pid, tree=args.tree, session=args.session,
                            prefer=[args.id] if args.id else None)
        if not leaf:
            print("no ready leaf available — either the graph is dry or siblings hold them all")
            return 1
    else:
        if not args.id:
            die("name a leaf, or use --next to take whichever one is free", code=64)
        leaf = g.claim(args.id, args.actor, pid=args.pid, tree=args.tree, session=args.session)
    events.emit(cfg, "leaf.claimed", {"leaf": leaf["id"], "actor": leaf.get("actor"),
                "claim_pid": leaf.get("claim_pid"), "tree": leaf.get("claim_tree"),
                "how": "next" if args.next else "named"})
    print("claimed %s as %s (pid %s)" % (leaf["id"], leaf.get("actor"), leaf.get("claim_pid")))
    return 0


def cmd_release(args):
    cfg = _cfg(args)
    _graph(cfg).release(args.id, args.reason or "released")
    events.emit(cfg, "leaf.released", {"leaf": args.id, "reason": args.reason or "released"})
    print("released %s back to ready" % args.id)
    return 0


def cmd_park(args):
    cfg = _cfg(args)
    _graph(cfg).park(args.id, args.reason)
    events.emit(cfg, "leaf.parked", {"leaf": args.id, "reason": args.reason})
    print("parked %s — the claim survives; a Crawler at a usage limit is not dead." % args.id)
    return 0


def cmd_unpark(args):
    cfg = _cfg(args)
    _graph(cfg).unpark(args.id)
    events.emit(cfg, "leaf.unparked", {"leaf": args.id})
    print("unparked %s" % args.id)
    return 0


def cmd_close(args):
    cfg = _cfg(args)
    g = _graph(cfg)
    leaf, notes = gates.close_gate(
        cfg, g, args.id, args.proof, args.reason, refuted=args.refuted,
        evidence=args.evidence, stale_proof_reason=args.stale_proof_reason,
        premise=args.premise, premise_read=args.premise_read)
    events.emit(cfg, "leaf.closed", {"leaf": leaf["id"], "outcome": "refuted" if args.refuted else "closed",
                "proof": leaf.get("proof"), "premise": args.premise, "actor": leaf.get("actor")})
    print("%s %s (%s)" % ("REFUTED" if args.refuted else "closed", leaf["id"], leaf.get("proof")))
    # Spin the Crawler down as soon as its leaf closes: mark it finished and close its room.
    # The process is left alone here on purpose — it is mid-call at this exact moment, having
    # just run this very command. `reap` takes it if it is still alive after the grace window.
    for done in campaign.finish(cfg, leaf["id"]):
        print("  %sspun down %s — %s%s" % (DIM, done["crawler"], done["channel"], OFF))
    for n in notes:
        print("  %s%s%s" % (DIM, n, OFF))
    return 0


def cmd_stop_gate(args):
    cfg = _cfg(args)
    # WHOSE turn-end is this? --leaf is exact and spawn bakes it into each Crawler's trigger.
    # Falling back to the tree: GAME_LOOP_REPO is set by the harness that invokes this trigger
    # and names the tree it is running in, which beats cwd because a trigger's working directory
    # belongs to whoever runs it. cwd last, for a hand-wired setup with no harness.
    tree = args.tree or os.environ.get("GAME_LOOP_REPO") or os.getcwd()
    ok, msg = gates.stop_gate(cfg, _graph(cfg), leaf_id=args.leaf, tree=tree)
    (print if ok else eprint)(msg)
    return 0 if ok else 2


# ------------------------------------------------------------------- lock
def cmd_lock_status(args):
    cfg = _cfg(args)
    ls = locks.LockSet(cfg)
    names = [args.resource] if args.resource else ls.names()
    if not names:
        print("no resources configured")
        return 0
    for name in names:
        state, h = ls.lock(name).state()
        if state == locks.FREE:
            print("%-14s FREE" % name)
        else:
            print("%-14s %s by pid %s (%s) since %s" % (name, state, h.get("pid"), h.get("who"), h.get("ts")))
    return 0


def _stamp(ts):
    """An epoch second is a number a reader has to go and convert. `since 1786738962` was
    printed to a human deciding whether to take somebody's worktree, which is a decision about
    how long ago something happened."""
    try:
        import datetime
        return datetime.datetime.fromtimestamp(int(ts)).isoformat(timespec="seconds")
    except (TypeError, ValueError):
        return str(ts or "?")


def _short(sid):
    """Abbreviate a session id, and SAY that it is abbreviated. `sess-AAAA` came out as
    `sess-AAA` — eight characters of a nine-character id, indistinguishable from the whole
    thing, in a report whose entire job is telling two sessions apart."""
    sid = sid or ""
    if not sid:
        return "?"
    return sid if len(sid) <= 12 else sid[:12] + "…"


def cmd_worktree_enter(args):
    """SessionStart hook shape. ALWAYS exits 0 — see below.

    Exit 0 unconditionally, including on a detected hijack, and that is not timidity. A
    SessionStart hook cannot deny a session; a non-zero exit here would abort the session's
    startup over a condition this leaf explicitly does not yet enforce, which is a gate built
    before its failure was observed. The teeth are WL-05, on PreToolUse, where a refusal
    actually maps onto the event.
    """
    cfg = _cfg(args)
    session = args.session or os.environ.get("SHOWRUNNER_SESSION") or ""
    verdict, detail = lease.enter(cfg, session, path=args.path, who=args.holder)
    tree = detail.get("tree")
    h = detail.get("holder") or {}

    if verdict == "not-a-worktree":
        return 0
    if verdict == "own":
        print("showrunner: you already hold worktree %s" % tree)
        return 0
    if verdict == "acquired":
        print("showrunner: worktree %s is yours (liveness basis: %s)"
              % (tree, h.get("pid_basis") or "?"))
    elif verdict == "reclaimed":
        prev = detail.get("previous") or {}
        print("showrunner: worktree %s was held by a session that is NOT alive (pid %s, "
              "session %s) — reclaimed.\n  Its work may still be in the tree. Nothing here "
              "deleted anything." % (tree, prev.get("pid"), (prev.get("session") or "?")[:8]))
    elif verdict == "unreadable":
        print("showrunner: worktree %s holds an UNREADABLE pid (%r). It cannot be proved dead, "
              "so it will not be reclaimed — a partial write by a LIVE holder looks exactly "
              "like this.\n  Find out whether %s is still running, then `%s worktree takeover "
              "%s --reason \"<why>\"`."
              % (tree, (h.get("pid") or "")[:40], h.get("who") or "the holder",
                 brief.sr_bin(cfg), tree))
        return 0
    elif verdict == "no-liveness":
        print("showrunner: no session process could be resolved, so a lease here would have no "
              "liveness at all and was NOT taken (%s).\n  This tree is unprotected; that is "
              "said out loud rather than left to look like success." % h.get("why", ""))
        return 0
    elif verdict == "hijack":
        print(lease.OPTIONS.format(
            who=h.get("who") or "?", session=_short(h.get("session")),
            pid=h.get("pid"), since=_stamp(h.get("ts")),
            basis=h.get("pid_basis") or "unrecorded",
            sr=brief.sr_bin(cfg), tree=tree))

    # WHAT A WORKTREE DOES NOT ISOLATE, printed from the audit rather than restated here.
    # Restating it is how the two copies drift, and worktree.audit_shared is the one that gets
    # maintained because spawn already depends on it.
    shares = worktree.audit_shared(cfg)
    if shares and verdict in ("acquired", "reclaimed", "hijack"):
        print("\n  A lease covers this TREE. Still shared with every sibling:")
        for item in shares:
            print("    - %s" % item["what"])
    return 0


def cmd_worktree_fork(args):
    """Your own tree, from the same commit the held one started at. Exit 2 on refusal."""
    cfg = _cfg(args)
    session = args.session or os.environ.get("SHOWRUNNER_SESSION") or ""
    try:
        path, d = lease.fork(cfg, getattr(args, "from"), session, base=args.base, name=args.name)
    except Refused as exc:
        die(str(exc), code=2)
    print("forked %s -> %s" % (d["from"], d["tree"]))
    # Resolved, and described as what it IS rather than as what it usually is. This said
    # "the commit X started at, not HEAD" unconditionally, which is false the moment somebody
    # passes --base HEAD — the line then argued with itself in the same breath.
    print("  base    %s  (%s)" % (
        d["base"][:12],
        "explicit --base" if args.base else "the commit %s started at" % d["from"]))
    print("  path    %s" % rel(path, cfg.root))
    print("  lease   held by you")
    for line in d.get("injected") or []:
        print("  inject  %s" % line)
    for line in d.get("warnings") or []:
        print("  note    %s" % line)
    return 0


def cmd_lease_status(args):
    """What holds each worktree. Read-only, and it prints the BASIS of every liveness claim.

    A lease's pid is discovered by walking a hook's ancestry rather than handed over (WL-01),
    and that walk can land on a weaker fact. Printing the state without the basis would show
    HELD in the same shape whether the process was identified or merely guessed at, which is
    the reader forming a belief the data does not support.
    """
    cfg = _cfg(args)
    rows = lease.status(cfg, args.tree)
    if not rows:
        print("no worktree leases (nothing has entered a managed worktree, or none exist)")
        return 0
    for r in rows:
        h = r["holder"] or {}
        if r["state"] == locks.FREE:
            print("%-28s FREE" % r["tree"])
            continue
        basis = r.get("pid_basis") or "?"
        print("%-28s %s by pid %s (%s) session %s since %s"
              % (r["tree"], r["state"], h.get("pid"), h.get("who") or "?",
                 (h.get("session") or "?")[:8], h.get("ts")))
        print("%-28s   liveness basis: %s%s"
              % ("", basis,
                 "  ← the session process was NOT identified; this pid is its parent, so a "
                 "dead session may still read as HELD" if basis == "ppid-fallback" else ""))
        if not r["exists"]:
            print("%-28s   NOTE: %s no longer exists on disk, but the lease does — a lease "
                  "outliving its tree is stale state, not a holder" % ("", r["path"]))
    return 0


def cmd_lock_acquire(args):
    cfg = _cfg(args)
    lock = locks.LockSet(cfg).lock(args.resource)
    ok = lock.acquire(os.getpid(), args.holder, session=args.session, wait=args.wait)
    if not ok:
        _, h = lock.state()
        events.emit(cfg, "lock.refused", {"resource": args.resource, "who": args.holder,
                                          "held_by": h.get("who"), "held_pid": h.get("pid"),
                                          "path": "acquire"})
        eprint("BLOCKED: %r held by pid %s (%s)" % (args.resource, h.get("pid"), h.get("who")))
        return 2
    events.emit(cfg, "lock.acquired", {"resource": args.resource, "who": args.holder,
                                       "lock_pid": os.getpid(), "path": "acquire"})
    print("ACQUIRED %s (pid %s — %s)" % (args.resource, os.getpid(), args.holder))
    eprint("NOTE: the holder recorded is THIS shell, which exits immediately. `lock run` is the "
           "authoritative path — there the holder is the consumer process itself.")
    return 0


def cmd_lock_release(args):
    cfg = _cfg(args)
    lock = locks.LockSet(cfg).lock(args.resource)
    if lock.release(pid=args.pid or os.getpid(), force=args.force):
        events.emit(cfg, "lock.released", {"resource": args.resource, "forced": bool(args.force),
                                           "path": "release"})
        print("released %s" % args.resource)
        return 0
    print("%s was not held" % args.resource)
    return 0


def cmd_lock_guard(args):
    cfg = _cfg(args)
    command = " ".join(args.command)
    allow, msg = locks.LockSet(cfg).guard(command, session=args.session or os.environ.get("SHOWRUNNER_CRAWLER"))
    if allow:
        print(msg)
        return 0
    eprint(msg)
    return 2


def cmd_lock_run(args):
    cfg = _cfg(args)
    lock = locks.LockSet(cfg).lock(args.resource)
    cmd = args.command
    if cmd and cmd[0] == "--":
        cmd = cmd[1:]
    if not cmd:
        die("nothing to run — usage: `showrunner lock run <resource> --holder <who> -- <cmd...>`",
            code=64)
    if not lock.acquire(os.getpid(), args.holder, session=args.session, wait=args.wait):
        _, h = lock.state()
        events.emit(cfg, "lock.refused", {"resource": args.resource, "who": args.holder,
                                          "held_by": h.get("who"), "held_pid": h.get("pid"),
                                          "path": "run", "waited": args.wait})
        eprint("BLOCKED: %r held by pid %s (%s). One consumer at a time."
               % (args.resource, h.get("pid"), h.get("who")))
        return 2
    events.emit(cfg, "lock.acquired", {"resource": args.resource, "who": args.holder,
                                       "lock_pid": os.getpid(), "path": "run"})
    rc = None
    try:
        import subprocess
        rc = subprocess.call(cmd, cwd=cfg.root)
        return rc
    finally:
        lock.release(pid=os.getpid(), force=True)
        # In the FINALLY, so a consumer killed mid-command still reports the release that
        # actually happened. A view that shows a resource held by a process that died is the
        # stale-lock confusion this whole module exists to prevent, one layer out.
        events.emit(cfg, "lock.released", {"resource": args.resource, "who": args.holder,
                                           "path": "run", "exit": rc})


# ------------------------------------------------------------- route/plan
def cmd_route(args):
    cfg = _cfg(args)
    g = _graph(cfg)
    leaves = [g.show(i) for i in args.id] if args.id else g.ready()
    decisions = [lanes.route(cfg, leaf) for leaf in leaves]
    path = lanes.log(cfg, decisions)
    for d in decisions:
        colour = "" if d["matched"] else YEL
        print("%s%s%s" % (colour, d.line(), OFF))
    print("%slogged to %s%s" % (DIM, rel(path, cfg.root), OFF))
    unmatched = [d for d in decisions if not d["matched"]]
    if unmatched:
        print("%s%d leaf/leaves matched no lane rule and defaulted. That is a missing rule, not a "
              "neutral outcome.%s" % (YEL, len(unmatched), OFF))
    return 0


def cmd_plan(args):
    cfg = _cfg(args)
    g = _graph(cfg)
    ready = g.ready()
    if not ready:
        print("no ready work — `showrunner ready` is dry")
        return 0
    decisions = {leaf["id"]: lanes.route(cfg, leaf) for leaf in ready}
    headless = [l for l in ready if decisions[l["id"]]["lane"] == lanes.HEADLESS]
    serialized = [l for l in ready if decisions[l["id"]]["lane"] != lanes.HEADLESS]

    waves, estimates, notes = collide.plan_waves(cfg, headless)
    print("%sheadless lane%s — %d ready leaf/leaves in %d wave(s)" % (BOLD, OFF, len(headless), len(waves)))
    for i, wave in enumerate(waves, 1):
        print("  wave %d: %s" % (i, ", ".join(wave)))
        for leaf_id in wave:
            est = estimates[leaf_id]
            print("    %s%-16s %s%s" % (DIM, leaf_id, est["basis"], OFF))
    for note in notes:
        print("  %s%s%s" % (YEL, note, OFF))

    if serialized:
        print("%sserialized lane%s — %d leaf/leaves, one at a time:" % (BOLD, OFF, len(serialized)))
        for leaf in serialized:
            d = decisions[leaf["id"]]
            print("  %-16s resource=%-10s %s" % (leaf["id"], d.get("resource") or "?", d["why"]))
    if args.json:
        print(json.dumps({
            "waves": waves,
            "serialized": [l["id"] for l in serialized],
            "estimates": {k: {"paths": sorted(v["paths"]), "shared": sorted(v["shared"]),
                              "basis": v["basis"]} for k, v in estimates.items()},
            "notes": notes,
        }, indent=2, sort_keys=True))
    return 0


# ------------------------------------------------------------------ spawn
def cmd_spawn(args):
    cfg = _cfg(args)
    g = _graph(cfg)
    leaf = g.show(args.id)
    decision = lanes.route(cfg, leaf)
    lanes.log(cfg, [decision])

    if not decision["matched"]:
        eprint("%sNOTE: %s%s" % (YEL, decision["why"], OFF))

    # A REHEARSAL THAT BUILDS THE ROOM POISONS THE RUN IT REHEARSED. `--dry-run` documented
    # itself as "see the command and start nothing", and started no SESSION while still
    # creating the worktree, the branch, the scratch dir and the claim — so the honest first
    # move (rehearse, read the argv, then launch) left the room already built and the real
    # spawn refused it. The preview now previews.
    if getattr(args, "dry_run", False) and not getattr(args, "launch", False):
        die("--dry-run applies to --launch; it shows the command a launch WOULD run.\n"
            "Without --launch there is nothing to rehearse.", code=64)
    if getattr(args, "dry_run", False):
        session = args.session or dispatch.new_session_id()
        model = dispatch.resolve_model(cfg, decision)
        cmd = dispatch.build_command(cfg, {"crawler": worktree.crawler_name(leaf["id"], args.actor)},
                                     model, session, "<brief>")
        print("%sDispatch (dry run — NOTHING created: no worktree, branch, scratch, brief or "
              "claim)%s" % (BOLD, OFF))
        print("  lane     %s" % decision["lane"])
        print("  model    %s" % (model or "(inherited)"))
        print("  command  %s" % " ".join(cmd))
        return 0

    record = worktree.spawn(cfg, leaf, actor=args.actor, base=args.base, branch=args.branch)
    # The channel is named before the brief is written, so the brief can TELL the Crawler
    # where to reach the orchestrator. A room the agent is never told about is a room it
    # never joins, which is indistinguishable from one that was never opened.
    chat_channel = dispatch.channel_for(cfg, record) if getattr(args, "launch", False) else None
    text = brief.build(cfg, leaf, record, decision,
                       orchestrator_findings=args.finding or None,
                       chat_channel=chat_channel)
    brief_path = brief.write(cfg, record, text)

    # Generated here, before the claim, so the claim, the campaign record and the process all
    # name one session. Reading it back from a launched process would leave a window in which
    # the claim names nothing and a live agent cannot be reaped.
    session = args.session
    if getattr(args, "launch", False) and not session:
        session = dispatch.new_session_id()

    entry = campaign.record_spawn(cfg, record, pid=args.pid, session=session)

    if not args.no_claim:
        g.claim(leaf["id"], args.actor, pid=args.pid, tree=record["worktree"], session=session)

    print("%sCrawler %s%s" % (BOLD, record["crawler"], OFF))
    print("  leaf     %s — %s" % (leaf["id"], leaf.get("title", "")))
    print("  lane     %s%s" % (decision["lane"],
                               " (resource %s)" % decision["resource"] if decision.get("resource") else ""))
    print("  worktree %s" % rel(record["worktree"], cfg.root))
    print("  branch   %s" % record["branch"])
    print("  scratch  %s" % rel(record["scratch"], cfg.root))
    for line in record["injected"]:
        print("  inject   %s" % line)
    for line in record.get("provisioned") or []:
        print("  harness  %s" % line)
    print("  brief    %s" % rel(brief_path, cfg.root))
    print("\n%sShares with siblings (a worktree isolates tracked files and nothing else):%s" % (BOLD, OFF))
    for item in record["shares"]:
        print("  - %s" % item["what"])
    if record.get("harness_gap"):
        eprint("\n%sHARNESS GAP: %s%s" % (YEL, record["harness_gap"], OFF))

    if getattr(args, "launch", False) or getattr(args, "dry_run", False):
        if record.get("harness_gap") and not args.dry_run:
            die("refusing to start a session in a tree with a harness gap: %s\n"
                "A Crawler without its own rails cannot gate its own commits, and under fan-out "
                "nobody is watching it." % record["harness_gap"], code=2)
        out = dispatch.launch(cfg, record, decision, text, session,
                              dry_run=bool(getattr(args, "dry_run", False)))
        # THE CLAIM'S LIVENESS MUST NAME THE SESSION, NOT THE SHELL. The claim is taken before
        # the process exists, so until now it recorded whichever shell ran `spawn` — which is
        # gone seconds later, making `reap --apply` release a leaf whose Crawler is still
        # working. Rebind it the moment the real pid is known.
        if out.get("launched") and out.get("pid") and not args.no_claim:
            g.rebind_claim(leaf["id"], out["pid"])
        print("\n%sDispatch%s" % (BOLD, OFF))
        print("  model    %s" % (out["model"] or "(inherited — no lane model declared)"))
        print("  session  %s" % out["session"])
        if out.get("channel"):
            print("  chat     %s" % out["channel"])
        elif out.get("chat"):
            eprint("  %schat     not wired: %s%s" % (YEL, out["chat"], OFF))
        if out["launched"]:
            print("  pid      %s" % out["pid"])
            print("  log      %s" % out["log"])
        else:
            print("  command  %s" % " ".join(out["cmd"][:2] + ["<brief>"] + out["cmd"][3:]))
            print("  (dry run — nothing started)")
    return 0


def cmd_edit(args):
    cfg = _cfg(args)
    g = _graph(cfg)
    body = args.body
    if args.body_file:
        with open(args.body_file) as fh:
            body = fh.read()
    leaf = g.edit(args.id, title=args.title, body=body,
                  paths=(args.path.split(",") if args.path else None))
    print("edited %s" % leaf["id"])
    print("  title %s" % leaf.get("title"))
    print("  body  %d chars" % len(leaf.get("body") or ""))
    return 0


def cmd_brief(args):
    cfg = _cfg(args)
    g = _graph(cfg)
    leaf = g.show(args.id)
    data = campaign.load(cfg)
    entry = next((c for c in data.get("crawlers", []) if c.get("leaf") == leaf["id"]), None)
    if not entry:
        die("no Crawler spawned for %s yet — run `showrunner spawn %s`" % (leaf["id"], leaf["id"]),
            code=2)
    entry = dict(entry)
    entry["worktree"] = cfg.abspath(entry["worktree"])
    entry["scratch"] = cfg.abspath(entry["scratch"])
    entry["shares"] = worktree.audit_shared(cfg)
    print(brief.build(cfg, leaf, entry, lanes.route(cfg, leaf),
                      orchestrator_findings=args.finding or None))
    return 0


# --------------------------------------------------- lifecycle / integrate
def cmd_reap(args):
    cfg = _cfg(args)
    g = _graph(cfg)
    actions, warnings = campaign.reap(cfg, g, base=args.base, apply=args.apply)
    for w in warnings:
        print("%swarn%s %s" % (YEL, OFF, w))
    if not actions:
        print("nothing to reap — every claim and lock has a live owner")
        return 0
    for a in actions:
        target = a.get("leaf") or a.get("resource") or a.get("crawler")
        print("%s%-8s%s %-24s %s" % (RED, a["kind"], OFF, target, a["why"]))
        print("         → %s" % a["action"])
    if not args.apply:
        print("\n%sdry run — re-run with --apply to reclaim.%s" % (DIM, OFF))
        print("Reclaim is deliberately loud: a leaf that was claimed and abandoned is evidence "
              "about the work or the harness, and a run that quietly re-queues it three times "
              "has learned nothing.")
    return 0


def cmd_reconcile(args):
    cfg = _cfg(args)
    findings = campaign.reconcile(cfg, _graph(cfg), base=args.base)
    if not findings:
        print("no Crawlers on record")
        return 0
    if args.json:
        print(json.dumps(findings, indent=2, sort_keys=True))
        return 0
    for f in findings:
        colour = RED if f["verdict"].startswith("ABANDONED") else (
            GRN if f["verdict"].startswith(("MERGED", "LIVE")) else YEL)
        print("%s%-28s%s %s" % (colour, f["crawler"], OFF, f["verdict"]))
        print("    leaf %s (%s) · branch %s%s" % (
            f["leaf"], f["leaf_status"], f["branch"], "" if f["branch_exists"] else " [gone]"))
        if f["uncommitted"]:
            print("    %d uncommitted change(s) in %s — inspect before deleting anything"
                  % (len(f["uncommitted"]), f["worktree"]))
        if f["scratch_files"]:
            print("    scratch holds %d file(s): %s" % (len(f["scratch_files"]),
                                                        ", ".join(f["scratch_files"][:5])))
        if f.get("harness_mis_certified"):
            # Retrospective and unrecoverable elsewhere: the harness verb is stateless, so once
            # a branch is merged nothing can be asked about the tree it was merged from.
            eprint("    %sMIS-CERTIFIED: a harness before game_loop #66 called this tree clean, "
                   "exit 0. Check whether this branch was ever integrated.%s" % (YEL, OFF))
    return 0


def cmd_watch(args):
    """Replay the event journal, then follow it. One JSON object per line, on stdout.

    THE READ SIDE OF THE BOUNDARY. A viewer must never tail `.showrunner/events.jsonl` itself:
    that file's name, location and rotation are showrunner's private business, and a consumer
    that reaches past this verb is the coupling `harness.py` deleted a hardcoded rule list to
    stop having. It asks; showrunner answers.

    REPLAY FIRST, ALWAYS. A viewer that attaches to a running campaign and sees nothing until
    the next transition cannot tell a quiet orchestrator from a broken pipe — and the quiet one
    is normal, since orchestration is bursty by nature. `--since <seq>` is how a reconnecting
    viewer asks for only what it missed, which is the same question with a different starting
    point rather than a different mode.

    EVERY FRAME CARRIES ITS OWN TYPE, including the ones that are not events: `ready` marks the
    end of replay, `heartbeat` proves the stream is alive during a quiet stretch, and `bye`
    marks a clean end. A stream that simply stops is indistinguishable from one that died, so
    the absence of `bye` is the signal — never end-of-file.
    """
    cfg = _cfg(args)
    # A CURSOR NAMES ITS INSTANCE; a bare integer does not. Several showrunners in several places
    # is the shape this whole surface exists for, and `seq` counts within one journal — so a
    # viewer holding two streams could resume one from the other's position, with both values
    # integers, the comparison succeeding, and no symptom anywhere.
    since, err = events.parse_cursor(cfg, args.since)
    if err:
        die(err, code=2)
    backlog, bad, unreadable = events.read(cfg, since_seq=since, limit=args.limit)
    if unreadable:
        # NOT an empty replay. "I cannot see this campaign" and "this campaign has done nothing"
        # are different answers, and only one of them is safe to render as an idle dashboard.
        die("the event journal exists and could not be read (%s). Refusing to stream a clean "
            "empty replay over it: a viewer cannot tell that from a campaign that has done "
            "nothing, and would show an orchestrator mid-fan-out as idle."
            % events.path_for(cfg), code=2)
    for ev in backlog:
        print(json.dumps(ev, sort_keys=True), flush=True)
    seq = backlog[-1]["seq"] if backlog else (since or 0)
    # A torn or corrupt line is REPORTED rather than skipped: a viewer that silently drops them
    # shows a campaign with holes in it and calls that the truth.
    print(json.dumps({"type": "ready", "replayed": len(backlog), "unparseable": bad,
                      "seq": seq, "cursor": events.cursor(cfg, seq),
                      "instance": events.instance_id(cfg),
                      "project": cfg.project_name}, sort_keys=True), flush=True)
    if not args.follow:
        return 0

    import time
    last_beat = 0.0
    try:
        while True:
            fresh, bad, unreadable = events.read(cfg, since_seq=seq)
            for ev in fresh:
                print(json.dumps(ev, sort_keys=True), flush=True)
                seq = max(seq, ev.get("seq", seq))
            nowt = time.time()
            if nowt - last_beat >= args.heartbeat:
                last_beat = nowt
                # The journal is SPARSE by design — it records decisions, and an orchestrator can
                # spend twenty minutes integrating without making one. A view built on the journal
                # alone freezes exactly when the work is hardest, which is when somebody is most
                # likely to be watching it. The heartbeat carries the cheap live counters so the
                # picture keeps moving without inventing events that did not happen.
                # `unreadable` rides every heartbeat rather than only the attach: a journal
                # can become unreadable long after a viewer connected, and the stream would
                # otherwise go quiet in exactly the way a finished campaign does.
                print(json.dumps({"type": "heartbeat", "ts": int(nowt), "seq": seq,
                                  "cursor": events.cursor(cfg, seq),
                                  "dropped": events.dropped(),
                                  "unreadable": unreadable,
                                  "unparseable": bad}, sort_keys=True), flush=True)
            time.sleep(args.interval)
    except KeyboardInterrupt:
        print(json.dumps({"type": "bye", "seq": seq, "reason": "interrupted"}, sort_keys=True),
              flush=True)
        return 0


def cmd_waiting(args):
    cfg = _cfg(args)
    is_waiting, detail = campaign.waiting(cfg, _graph(cfg), base=args.base)
    if args.porcelain:
        print(json.dumps(detail, indent=2, sort_keys=True))
    else:
        if is_waiting:
            print("WAITING on %d live and %d parked Crawler(s):"
                  % (len(detail["live_crawlers"]), len(detail["parked_crawlers"])))
            for c in detail["live_crawlers"]:
                print("  live   %s (%s)" % (c["crawler"], c["leaf"]))
            for c in detail["parked_crawlers"]:
                print("  parked %s (%s) — %s" % (c["crawler"], c["leaf"], c["why"]))
        else:
            print("not waiting — no dispatched work has a live owner or an explicit park")
        # PRINTED ON BOTH BRANCHES, because a blocked Crawler is the reason this can say NOT
        # waiting while Crawlers are alive, and a verdict whose cause is invisible is one the
        # reader argues with. These are the sessions somebody has to go and prompt.
        for c in detail.get("blocked_crawlers") or []:
            eprint("  %sBLOCKED%s %s (%s) — %s. Alive and doing nothing; it needs a message, "
                   "not time." % (YEL, OFF, c["crawler"], c["leaf"], c["why"]))
    return 0 if is_waiting else 1


def cmd_baseline(args):
    cfg = _cfg(args)
    if not (cfg.get("checks") or []):
        die("no checks configured — a baseline of nothing proves nothing", code=2)
    data = gates.record_baseline(cfg)
    print("recorded baseline at %s" % rel(cfg.baseline_path, cfg.root))
    for c in data["checks"]:
        print("  %-16s rc=%-3s %d failure line(s) [%s]" % (c["name"], c["rc"], len(c["failures"]),
                                                           c["resolution"]))
    print("%sThe criterion from here is NO NEW FAILURES versus this, never 'all green' — a repo "
          "with pre-existing failures cannot satisfy 'all green', so that gate gets switched off "
          "on contact with a real codebase.%s" % (DIM, OFF))
    return 0


def cmd_check(args):
    cfg = _cfg(args)
    current = gates.run_checks(cfg)
    ok, report = gates.compare_to_baseline(cfg, current, gates.load_baseline(cfg))
    for line in report:
        print(line)
    if ok is None:
        return 1
    return 0 if ok else 2


def cmd_integrate(args):
    cfg = _cfg(args)
    results, ok = campaign.integrate(cfg, _graph(cfg), base=args.base, only=args.only or None,
                                     dry_run=args.dry_run)
    if not results:
        print("nothing to integrate — no closed Crawler branch is unmerged")
        return 0
    for r in results:
        colour = GRN if r["status"] in ("integrated", "would-merge") else RED
        print("%s%-12s%s %s (%s)" % (colour, r["status"], OFF, r["branch"], r["crawler"]))
        for line in r.get("report") or []:
            print("    %s" % line)
        if r.get("detail"):
            print("    %s" % r["detail"].replace("\n", "\n    "))
        if r.get("note"):
            print("    %s%s%s" % (YEL, r["note"], OFF))
    if not ok:
        eprint("\nSTOPPED on the first failure rather than stacking branches onto a broken trunk. "
               "A branch is integrated only when the checks pass on the MERGED result.")
        return 2
    integrated = [r for r in results if r["status"] == "integrated"]
    if integrated:
        print("%sThese merges auto-committed, so no provenance declaration was needed: the "
              "harness's commit gate matches `git commit`, which a clean merge never runs. "
              "Declare only when you commit a resolution yourself.%s" % (DIM, OFF))
        proofs = [r["merged_proof"] for r in integrated if r.get("merged_proof")]
        if proofs:
            print("\n%sChecks on the MERGED result, written out so they can be cited:%s" % (BOLD, OFF))
            for p_ in proofs:
                print("  %s" % rel(p_, cfg.root))
            print("%sA fix proved on a branch does NOT transfer: the harness scopes a proved fix "
                  "to the session that proved it, so a Crawler's proof cannot satisfy your "
                  "handback — by design. Branch-green is not trunk-green. If a leaf claimed a "
                  "fix, exercise that fix's own consumer against the merged trunk and prove it "
                  "here.%s" % (DIM, OFF))
    return 0


def cmd_integration_commit(args):
    cfg = _cfg(args)
    data = campaign.load(cfg)
    entries = []
    for name in args.crawler or []:
        entry = next((c for c in data.get("crawlers", [])
                      if c.get("crawler") == name or c.get("leaf") == name), None)
        if not entry:
            die("no Crawler on record named %r" % name, code=2)
        entries.append({"crawler": entry["crawler"], "branch": entry["branch"]})
    for br in args.branch or []:
        entries.append({"crawler": br, "branch": br})
    if not entries:
        die("name at least one --crawler or --branch whose work this commit lands", code=2)

    decl = gates.declare_integration(cfg, entries, base=args.base)
    print("declared %s" % rel(decl["path"], cfg.root))
    print("  crawlers: %s" % ", ".join(sorted(decl["crawlers"])))
    print("  expected %d file(s) from the merged Crawlers; %d staged"
          % (len(decl["expected_files"]), len(decl["staged_files"])))
    if decl["unexplained"]:
        eprint("%sUNEXPLAINED: %d staged file(s) no named Crawler ever touched:%s"
               % (RED, len(decl["unexplained"]), OFF))
        for p in decl["unexplained"][:20]:
            eprint("  %s" % p)
        eprint("This is the real orchestration failure the single-agent provenance check cannot "
               "see: not 'you didn't edit these' (you never do), but 'nobody did'.")
        return 2
    print("  %sok — every staged file is accounted for by a named Crawler%s" % (GRN, OFF))
    print("  trailer: %s" % gates.trailer(decl))

    att = gates.attribution(cfg, entries)
    if att:
        print("\n%sDeclare it to the harness so its provenance check asks the better question:%s"
              % (BOLD, OFF))
        print("  %s" % att["command"])
        print("  %sWHEN: %s%s" % (DIM, att["when"], OFF))
        print("  %sORDER: %s%s" % (DIM, att["order"], OFF))
    return 0


# ------------------------------------------------------------------ parser
def build_parser():
    p = argparse.ArgumentParser(prog="showrunner", description=__doc__)
    p.add_argument("--version", action="version", version="showrunner %s" % __version__)
    sub = p.add_subparsers(dest="cmd")

    s = sub.add_parser("init", help="write .showrunner/config.json and the worktree root")
    s.add_argument("--force", action="store_true")
    s.set_defaults(func=cmd_init)

    s = sub.add_parser("doctor", help="validate config; refuses configurations that degrade silently")
    s.set_defaults(func=cmd_doctor)

    s = sub.add_parser("status", help="the campaign at a glance")
    s.set_defaults(func=cmd_status)

    # graph
    s = sub.add_parser("add", help="add a leaf")
    s.add_argument("title")
    s.add_argument("--id")
    s.add_argument("--body")
    s.add_argument("--body-file")
    s.add_argument("--kind", default="task", choices=["task", "epic"])
    s.add_argument("--label", action="append")
    s.add_argument("--path", action="append")
    s.add_argument("--after", action="append", help="leaf id that must close first")
    s.set_defaults(func=cmd_add)

    s = sub.add_parser("dep", help="declare that CHILD is blocked by PARENT")
    s.add_argument("child")
    s.add_argument("parent")
    s.set_defaults(func=cmd_dep)

    s = sub.add_parser("list", help="list leaves")
    s.add_argument("--status")
    s.add_argument("--json", action="store_true")
    s.set_defaults(func=cmd_list)

    s = sub.add_parser("edit", help="correct a leaf's title, body or paths (the body IS the brief)")
    s.add_argument("id")
    s.add_argument("--title")
    s.add_argument("--body")
    s.add_argument("--body-file")
    s.add_argument("--path")
    s.set_defaults(func=cmd_edit)

    s = sub.add_parser("show", help="show one leaf")
    s.add_argument("id")
    s.set_defaults(func=cmd_show)

    s = sub.add_parser("ready", help="unblocked, unclaimed work — the only discovery entrypoint")
    s.add_argument("--json", action="store_true")
    s.set_defaults(func=cmd_ready)

    s = sub.add_parser("claim", help="claim a leaf (records owner liveness)")
    s.add_argument("id", nargs="?")
    s.add_argument("--next", action="store_true",
                   help="atomically take ANY ready leaf; exit 1 when none is free. Safe for "
                        "several orchestrators at once — losing a race means a sibling got "
                        "there first, which is the system working")
    s.add_argument("--actor", default="crawler")
    s.add_argument("--pid", type=int)
    s.add_argument("--tree")
    s.add_argument("--session")
    s.set_defaults(func=cmd_claim)

    s = sub.add_parser("release", help="release a claim back to ready")
    s.add_argument("id")
    s.add_argument("--reason")
    s.set_defaults(func=cmd_release)

    s = sub.add_parser("park", help="pause a claim (usage limit) — it survives the reaper")
    s.add_argument("id")
    s.add_argument("--reason", required=True)
    s.set_defaults(func=cmd_park)

    s = sub.add_parser("unpark", help="resume a parked claim under a new owner")
    s.add_argument("id")
    s.set_defaults(func=cmd_unpark)

    s = sub.add_parser("close", help="the proof-of-done gate")
    s.add_argument("id")
    s.add_argument("--proof")
    s.add_argument("--reason")
    s.add_argument("--refuted", action="store_true", help="the premise did not hold (a SUCCESS)")
    s.add_argument("--evidence", help="the file that refutes the premise")
    s.add_argument("--premise", choices=list(gates.PREMISE_VERDICTS))
    s.add_argument("--premise-read", help="the real file you checked the premise against")
    s.add_argument("--stale-proof-reason", help="why an artifact older than the claim is the proof")
    s.set_defaults(func=cmd_close)

    s = sub.add_parser("stop-gate", help="refuse a turn-end while YOUR claimed leaf is open")
    s.add_argument("--leaf", help="the leaf this caller holds; exact, and what spawn bakes in")
    s.add_argument("--tree", help="the caller's tree, matched against claim_tree "
                                  "(default: $GAME_LOOP_REPO, then cwd)")
    s.set_defaults(func=cmd_stop_gate)

    # locks
    s = sub.add_parser("lease", help="worktree leases — one session per tree")
    esub = s.add_subparsers(dest="leasecmd")
    t = esub.add_parser("status", help="what holds each worktree, and on what evidence")
    t.add_argument("tree", nargs="?")
    t.set_defaults(func=cmd_lease_status)

    s = sub.add_parser("worktree", help="the tree a session is standing in")
    wsub = s.add_subparsers(dest="worktreecmd")
    t = wsub.add_parser("enter", help="SessionStart: take this tree's lease, or report who holds it")
    t.add_argument("--session", help="the Claude Code session id (hooks supply it on stdin)")
    t.add_argument("--path", help="the tree to consider; defaults to the cwd")
    t.add_argument("--holder", help="a name for the holder; defaults to 'interactive'")
    t.set_defaults(func=cmd_worktree_enter)

    t = wsub.add_parser("fork", help="your own tree, off the same base as a held one")
    t.add_argument("--from", required=True, help="the held worktree to fork from")
    t.add_argument("--session", help="the Claude Code session id")
    t.add_argument("--base", help="override the base commit; refuses rather than guess one")
    t.add_argument("--name", help="a name for the new tree")
    t.set_defaults(func=cmd_worktree_fork)

    s = sub.add_parser("lock", help="single-consumer resource locks")
    lsub = s.add_subparsers(dest="lockcmd")

    t = lsub.add_parser("status")
    t.add_argument("resource", nargs="?")
    t.set_defaults(func=cmd_lock_status)

    t = lsub.add_parser("acquire")
    t.add_argument("resource")
    t.add_argument("--holder", default="manual")
    t.add_argument("--session")
    t.add_argument("--wait", type=float, default=0)
    t.set_defaults(func=cmd_lock_acquire)

    t = lsub.add_parser("release")
    t.add_argument("resource")
    t.add_argument("--pid", type=int)
    t.add_argument("--force", action="store_true")
    t.set_defaults(func=cmd_lock_release)

    t = lsub.add_parser("guard", help="PreToolUse shape: exit 2 blocks the tool call")
    t.add_argument("--session")
    t.add_argument("command", nargs=argparse.REMAINDER)
    t.set_defaults(func=cmd_lock_guard)

    t = lsub.add_parser("run", help="authoritative: acquire, exec, release — holder is the consumer")
    t.add_argument("resource")
    t.add_argument("--holder", default="run")
    t.add_argument("--session")
    t.add_argument("--wait", type=float, default=0)
    # nargs="*" AND NOT REMAINDER. REMAINDER takes everything after the first positional, so
    # `lock run device --holder crawler-a -- ./deploy.sh` — the form documented in the README,
    # for the one hard rule this project exists to enforce — put `--holder` into the COMMAND,
    # left holder at its default, and then tried to execute `--holder` as a program. Both flag
    # orders parse correctly with "*", and the `--` separator still works.
    t.add_argument("command", nargs="*")
    t.set_defaults(func=cmd_lock_run)

    # routing / planning
    s = sub.add_parser("route", help="show the lane each leaf routes to, and the rule that decided")
    s.add_argument("id", nargs="*")
    s.set_defaults(func=cmd_route)

    s = sub.add_parser("plan", help="group ready work into non-overlapping waves before fan-out")
    s.add_argument("--json", action="store_true")
    s.set_defaults(func=cmd_plan)

    # crawlers
    s = sub.add_parser("spawn", help="create a Crawler's worktree, scratch, injection and brief")
    s.add_argument("id")
    s.add_argument("--actor", default="crawler")
    s.add_argument("--base", default="HEAD")
    s.add_argument("--branch")
    s.add_argument("--pid", type=int)
    s.add_argument("--session")
    s.add_argument("--no-claim", action="store_true")
    s.add_argument("--launch", action="store_true",
                   help="start a REAL Claude Code session in the worktree, with its own hooks")
    s.add_argument("--dry-run", action="store_true",
                   help="with --launch: show what would start, and start nothing")
    s.add_argument("--finding", action="append",
                   help="something you already checked; the Crawler is asked to confirm or refute it")
    s.set_defaults(func=cmd_spawn)

    s = sub.add_parser("brief", help="print a Crawler's brief")
    s.add_argument("id")
    s.add_argument("--finding", action="append")
    s.set_defaults(func=cmd_brief)

    s = sub.add_parser("reap", help="reclaim claims and locks whose owners are dead")
    s.add_argument("--apply", action="store_true")
    s.add_argument("--base", default="HEAD")
    s.set_defaults(func=cmd_reap)

    s = sub.add_parser("reconcile", help="on resume: which branch is merged, abandoned, or live")
    s.add_argument("--base", default="HEAD")
    s.add_argument("--json", action="store_true")
    s.set_defaults(func=cmd_reconcile)

    s = sub.add_parser("watch", help="stream this campaign's events as JSON lines: replay, then "
                                     "follow. The read side of the observability boundary — a "
                                     "viewer asks this rather than tailing showrunner's files")
    s.add_argument("--follow", "-f", action="store_true", help="keep streaming after the replay")
    s.add_argument("--since", help="resume from a cursor (as handed back in `ready`) or a bare seq. A cursor from a DIFFERENT showrunner is refused, not silently used")
    s.add_argument("--limit", type=int, help="cap the replay to the last N events")
    s.add_argument("--interval", type=float, default=0.5, help="poll seconds while following")
    s.add_argument("--heartbeat", type=float, default=5.0,
                   help="seconds between heartbeat frames; the journal is sparse and a view "
                        "built on it alone freezes during long quiet work")
    s.set_defaults(func=cmd_watch)

    s = sub.add_parser("waiting",
                       help="exit 0 when this orchestrator is legitimately waiting on dispatched "
                            "work (a live Crawler PID or an explicit park), exit 1 otherwise — a "
                            "recomputable fact for an idle watchdog that cannot see subagents")
    s.add_argument("--base", default="HEAD")
    s.add_argument("--porcelain", action="store_true")
    s.set_defaults(func=cmd_waiting)

    s = sub.add_parser("baseline", help="record the current check results as the comparison point")
    s.set_defaults(func=cmd_baseline)

    s = sub.add_parser("check", help="run checks and compare: NO NEW FAILURES, not 'all green'")
    s.set_defaults(func=cmd_check)

    s = sub.add_parser("integrate", help="merge Crawler branches serially, checks after each")
    s.add_argument("--base")
    s.add_argument("--only", action="append")
    s.add_argument("--dry-run", action="store_true")
    s.set_defaults(func=cmd_integrate)

    s = sub.add_parser("integration-commit",
                       help="declare a merge commit's provenance: does the staged set match the "
                            "union of what the merged Crawlers edited?")
    s.add_argument("--crawler", action="append")
    s.add_argument("--branch", action="append")
    s.add_argument("--base", default="HEAD")
    s.set_defaults(func=cmd_integration_commit)

    return p


def main(argv=None):
    parser = build_parser()
    args = parser.parse_args(argv)
    if not getattr(args, "func", None):
        parser.print_help()
        return 64
    try:
        return args.func(args)
    except Refused as exc:
        # A MARKER ON THE CHANNEL A FILTER READS. The refusal itself belongs on stderr and
        # stays there — but every consumer of this CLI is an agent, this repo's own brief
        # tells them to run `showrunner close ...`, and agents pipe stdout aggressively to
        # protect context. A refusal that appears only on stderr is, to `... | grep -i done`,
        # indistinguishable from a command that did nothing and succeeded.
        #
        # One line, so the filter cannot swallow the fact that something happened. Not the
        # message: duplicating it would double every refusal for the humans reading both
        # streams, and the point is to stop silence, not to repeat the explanation.
        print("showrunner: REFUSED (exit %d) — reason on stderr" % exc.code)
        eprint("%s%s%s" % (RED, exc, OFF))
        if exc.hint:
            eprint("  %s" % exc.hint.replace("\n", "\n  "))
        return exc.code
    except BrokenPipeError:
        return 0
    except KeyboardInterrupt:
        return 130
